name: news_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  dio: ^4.0.0
  shared_preferences: ^2.0.8
  webview_flutter: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
